-- MySQL Script generated by MySQL Workbench
-- Вт 06 июн 2023 09:20:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WeatherAppDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WeatherAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WeatherAppDB` ;
USE `WeatherAppDB` ;

-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblUsers` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `surname` VARCHAR(40) NULL,
  `phone_number` BIGINT NULL,
  `mail` VARCHAR(100) NULL,
  `password` VARCHAR(30) NULL,
  `root` TINYINT NULL,
  `registr_date` DATE NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblAdminCodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblAdminCodes` (
  `admin_code_id` INT NOT NULL AUTO_INCREMENT,
  `adminID` INT NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_code_id`),
  INDEX `fk_tblAdminCodes_1_idx` (`adminID` ASC) ,
  CONSTRAINT `fk_tblAdminCodes_tblUsers`
    FOREIGN KEY (`adminID`)
    REFERENCES `WeatherAppDB`.`tblUsers` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblReplyWeather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblReplyWeather` (
  `reply_trigger_id` INT NOT NULL AUTO_INCREMENT,
  `celsius` TINYINT NULL,
  `humidity` INT NULL,
  `condition_` VARCHAR(40) NULL,
  `wind_speed` FLOAT NULL,
  PRIMARY KEY (`reply_trigger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblDefaultTriggers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblDefaultTriggers` (
  `default_trigger_id` INT NOT NULL AUTO_INCREMENT,
  `celsius_min` TINYINT NULL,
  `celsius_max` TINYINT NULL,
  `humidity_min` INT NULL,
  `humidity_max` INT NULL,
  `wind_speed_min` FLOAT NULL,
  `wind_speed_max` FLOAT NULL,
  PRIMARY KEY (`default_trigger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblCustomTriggers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblCustomTriggers` (
  `custom_trigger_id` INT NOT NULL AUTO_INCREMENT,
  `celsius_min` TINYINT NULL,
  `celsius_max` TINYINT NULL,
  `humidity_min` INT NULL,
  `humidity_max` INT NULL,
  `wind_speed_min` FLOAT NULL,
  `wind_speed_max` FLOAT NULL,
  PRIMARY KEY (`custom_trigger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblLocations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblLocations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `lat` FLOAT NULL,
  `lon` FLOAT NULL,
  `location_name` VARCHAR(200) NULL,
  `default_triggerID` INT NULL,
  `custom_triggerID` INT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `fk_tblLocations_tblDefaultTriggers_idx` (`default_triggerID` ASC) ,
  INDEX `fk_tblLocations_tblCustomTriggers_idx` (`custom_triggerID` ASC) ,
  CONSTRAINT `fk_tblLocations_tblDefaultTriggers`
    FOREIGN KEY (`default_triggerID`)
    REFERENCES `WeatherAppDB`.`tblDefaultTriggers` (`default_trigger_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tblLocations_tblCustomTriggers`
    FOREIGN KEY (`custom_triggerID`)
    REFERENCES `WeatherAppDB`.`tblCustomTriggers` (`custom_trigger_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblAutoRequestHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblAutoRequestHistory` (
  `auto_history_id` INT NOT NULL AUTO_INCREMENT,
  `locationID` INT NULL,
  `resp_time` DATETIME NULL,
  `reply_weatherID` INT NULL,
  `reply_time` DATETIME NULL,
  PRIMARY KEY (`auto_history_id`),
  INDEX `fk_tblAutoRequestHistory_1_idx` (`reply_weatherID` ASC) ,
  INDEX `fk_tblAutoRequestHistory_tblLocations_idx` (`locationID` ASC) ,
  CONSTRAINT `fk_tblAutoRequestHistory_tblReplyWeather`
    FOREIGN KEY (`reply_weatherID`)
    REFERENCES `WeatherAppDB`.`tblReplyWeather` (`reply_trigger_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tblAutoRequestHistory_tblLocations`
    FOREIGN KEY (`locationID`)
    REFERENCES `WeatherAppDB`.`tblLocations` (`location_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblLocationUserRelations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblLocationUserRelations` (
  `location_user_relation_id` INT NOT NULL AUTO_INCREMENT,
  `locationID` INT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`location_user_relation_id`),
  INDEX `fk_tblLocationUserRelations_1_idx` (`locationID` ASC) ,
  INDEX `fk_tblLocationUserRelations_2_idx` (`userID` ASC) ,
  CONSTRAINT `fk_tblLocationUserRelations_tblLocations`
    FOREIGN KEY (`locationID`)
    REFERENCES `WeatherAppDB`.`tblLocations` (`location_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tblLocationUserRelations_tblUsers`
    FOREIGN KEY (`userID`)
    REFERENCES `WeatherAppDB`.`tblUsers` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblCustomConditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblCustomConditions` (
  `custom_trigger_id` INT NOT NULL AUTO_INCREMENT,
  `condition_` VARCHAR(40) NULL,
  `custom_triggerID` INT NULL,
  PRIMARY KEY (`custom_trigger_id`),
  INDEX `fk_tblCustomConditions_1_idx` (`custom_triggerID` ASC) ,
  CONSTRAINT `fk_tblCustomConditions_tblCustomTriggers`
    FOREIGN KEY (`custom_triggerID`)
    REFERENCES `WeatherAppDB`.`tblCustomTriggers` (`custom_trigger_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherAppDB`.`tblDefaultConditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WeatherAppDB`.`tblDefaultConditions` (
  `default_condition_id` INT NOT NULL AUTO_INCREMENT,
  `condition_` VARCHAR(40) NULL,
  `default_triggerID` INT NULL,
  PRIMARY KEY (`default_condition_id`),
  INDEX `fk_tblDefaultConditions_1_idx` (`default_triggerID` ASC) ,
  CONSTRAINT `fk_tblDefaultConditions_tblDefaultTriggers`
    FOREIGN KEY (`default_triggerID`)
    REFERENCES `WeatherAppDB`.`tblDefaultTriggers` (`default_trigger_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
